server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 8192KB
      max-request-size: 8192KB
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop_sample_catalog
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
springdoc:
  packagesToScan: ru.vegxer.shopsample.catalog

app:
  attachment:
    thumbnail:
      size: 200
    location: attachments
